name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: /usr/local/cuda/lib64:$LD_LIBRARY_PATH  # Set library path for CUDA

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CUDA Toolkit
      run: apt-get update && apt-get install -y nvidia-cuda-toolkit

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: biodeg
        python-version: 3.11

    - name: Install Conda dependencies
      run: conda install cudatoolkit=10.0

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run tests
      run: poetry run pytest
